#include <ctype.h>
#include <stdio.h>
#include <string.h>

/* 

PROBLEM:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

NOTES:

steps:

- Start with the first two numbers: 0 and 1.
- Add them to get the next number.
- Keep track of the last two numbers.
- Repeat the process until you reach the desired position in the sequence.

even:

1 + 2 = 3
2 + 3 = 5
3 + 5 = 8
5 + 8 = 13
8 + 13 = 21
13 + 21 = 34

*/

// int fibSumEvenTerms(int evenTerm)
// {
//     int prevSum = 0;
// }

int main(void)
{
    int max = 4000000;
    int term1 = 1;
    int term2 = 2;
    int nextNum = 0;
    int finalEvenSum = 2;

    while (term2 < max)
    {
        nextNum = term1 + term2;
        term1 = term2;
        term2 = nextNum;

        if (nextNum % 2 == 0)
        {
            finalEvenSum += nextNum;
        }
    }
    printf("%d\n", finalEvenSum);
    return 0;
}

// int main(void)
// {
//     int term1 =  0;
//     int term2 = 2;
//     long max = 4000000000;
//     int fibonacciNum = 0;

//    for (int i = 0; fibonacciNum < max; i++)
//    {
//         int nextNum = term1 + term2;
//         term1 = term2;
//         term2 = nextNum;
//    }
//    fibonacciNum = term2;
//    printf("%d", fibonacciNum);
//    return 0;
// }