#include <ctype.h>
#include <stdio.h>
#include <string.h>

/* 

PROBLEM:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

NOTES:

steps:

- Start with the first two numbers: 0 and 1.
- Add them to get the next number.
- Keep track of the last two numbers.
- Repeat the process until you reach the desired position in the sequence.

even:

0 + 2 = 2
2 + 2 = 4
4 + 2 = 6
6 + 4 = 10
10 + 6 = 16
16 + 10 = 26

*/

// int fibSumEvenTerms(int evenTerm)
// {
//     int prevSum = 0;
// }

int main(void)
{
    int max = 4000000;
    int term1 = 0;
    int term2 = 2;
    int nextNum = 0;
    int fibNum = 0;

    while ((term1 < max) && (term2 < max))
    {
        nextNum = term1 + term2;
        term1 = term2;
        term2 = nextNum;
        fibNum = nextNum;
    }
    printf("%d\n", fibNum);
    return 0;
}

// int main(void)
// {
//     int term1 =  0;
//     int term2 = 2;
//     long max = 4000000000;
//     int fibonacciNum = 0;

//    for (int i = 0; fibonacciNum < max; i++)
//    {
//         int nextNum = term1 + term2;
//         term1 = term2;
//         term2 = nextNum;
//    }
//    fibonacciNum = term2;
//    printf("%d", fibonacciNum);
//    return 0;
// }